name: Standard Ruby

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  test:
    name: "Standard Ruby"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.2.2"
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          bundle update
      - name: Run Standard Ruby
        run: bundle exec standardrb
